name: Bug Report
description: Something isn't working right? Let us know so we can fix it.
labels: ["bug"]
body:
  - type: dropdown
    id: app-version
    attributes:
      label: App Version
      description: Which version of ShutterCoach are you using? (Check Settings > About)
      options:
        - "1.1"
        - "1.0"
        - "Not sure"
    validations:
      required: true

  - type: dropdown
    id: ios-version
    attributes:
      label: iOS Version
      description: Which iOS version is your device running?
      options:
        - "iOS 18.3"
        - "iOS 18.2"
        - "iOS 18.1"
        - "iOS 18.0"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly. What did you see?
      placeholder: "When I tap the critique button, the app freezes for a few seconds..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we see this bug ourselves?
      placeholder: |
        1. Open the app
        2. Go to...
        3. Tap on...
        4. See the issue
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
      description: What were you expecting instead?
      placeholder: "The critique should have loaded within a few seconds."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If it helps, add screenshots or screen recordings.
      placeholder: Drag and drop images here.
    validations:
      required: false
