name: Feature Request
description: Got an idea to make ShutterCoach better? We're all ears.
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What feature would you like?
      description: Describe your idea. What should it do?
      placeholder: "It would be great if the app could..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Why would this help?
      description: What problem does this solve or what would it make easier?
      placeholder: "Right now I have to... but with this feature I could..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Have you found any workarounds or other ways to achieve this?
      placeholder: "I've tried... but it doesn't quite work because..."
    validations:
      required: false
