name: General Feedback
description: Share your thoughts — praise, suggestions, questions, or anything else.
labels: ["feedback"]
body:
  - type: dropdown
    id: feedback-type
    attributes:
      label: What kind of feedback is this?
      options:
        - "Praise — something I love about the app"
        - "Suggestion — a small improvement idea"
        - "Question — I need help with something"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: message
    attributes:
      label: Your feedback
      description: Tell us what's on your mind.
      placeholder: "I really love how..."
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot (optional)
      description: Add a screenshot if it helps explain your feedback.
      placeholder: Drag and drop an image here.
    validations:
      required: false
